# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports
-   repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--settings-path=tools/.isort.cfg"]
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: ["--line-length=80"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        args: ["--config-file=tools/.mypy.ini"]
